-- Active: 1725528144290@@127.0.0.1@5432@postgres
CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    datetime_to_do TIMESTAMP WITH TIME ZONE NOT NULL,
    task_info TEXT NOT NULL
);